[build]
  publish = "."
  command = "node build.js"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors 'self' https://*.netlify.app https://decapcms.org; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://identity.netlify.com https://cdn.jsdelivr.net; connect-src 'self' https://*.netlify.com https://*.netlify.app https://api.github.com; img-src 'self' data: blob: https://*.netlify.app https://*.githubusercontent.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net;"
